import create from 'zustand'

const levels = [
  {
    mapHeight: 20,
    mapWidth: 20,
    levelColor: 'forestgreen',
    starCount: 10,
    obstacleCount: 5,
    wanderEnemyCount: 0,
    hunterEnemyCount: 0,
    spinnerEnemyCount: 0,
  },
  {
    mapHeight: 20,
    mapWidth: 20,
    levelColor: 'green',
    starCount: 15,
    obstacleCount: 15,
    wanderEnemyCount: 1,
    hunterEnemyCount: 0,
    spinnerEnemyCount: 0,
  },
  {
    mapHeight: 30,
    mapWidth: 30,
    levelColor: 'darkgreen',
    starCount: 30,
    obstacleCount: 25,
    wanderEnemyCount: 2,
    hunterEnemyCount: 0,
    spinnerEnemyCount: 0,
  },
  {
    mapHeight: 20,
    mapWidth: 40,
    levelColor: 'forestgreen',
    starCount: 30,
    obstacleCount: 20,
    wanderEnemyCount: 4,
    hunterEnemyCount: 0,
    spinnerEnemyCount: 0,
  },

  {
    mapHeight: 50,
    mapWidth: 50,
    levelColor: 'midnightblue',
    starCount: 15,
    obstacleCount: 15,
    wanderEnemyCount: 7,
    hunterEnemyCount: 1,
    spinnerEnemyCount: 0,
  },
  {
    mapHeight: 60,
    mapWidth: 60,
    levelColor: 'blue',
    starCount: 20,
    obstacleCount: 18,
    wanderEnemyCount: 8,
    hunterEnemyCount: 1,
    spinnerEnemyCount: 0,
  },
  {
    mapHeight: 60,
    mapWidth: 60,
    levelColor: 'darkblue',
    starCount: 40,
    obstacleCount: 5,
    wanderEnemyCount: 6,
    hunterEnemyCount: 2,
    spinnerEnemyCount: 0,
  },
  {
    mapHeight: 70,
    mapWidth: 30,
    levelColor: 'navy',
    starCount: 50,
    obstacleCount: 20,
    wanderEnemyCount: 8,
    hunterEnemyCount: 2,
    spinnerEnemyCount: 0,
  },

  {
    mapHeight: 40,
    mapWidth: 40,
    levelColor: 'rebeccapurple',
    starCount: 20,
    obstacleCount: 5,
    wanderEnemyCount: 0,
    hunterEnemyCount: 4,
    spinnerEnemyCount: 0,
  },
  {
    mapHeight: 35,
    mapWidth: 45,
    levelColor: 'indigo',
    starCount: 25,
    obstacleCount: 0,
    wanderEnemyCount: 7,
    hunterEnemyCount: 2,
    spinnerEnemyCount: 0,
  },
  {
    mapHeight: 40,
    mapWidth: 50,
    levelColor: 'purple',
    starCount: 25,
    obstacleCount: 8,
    wanderEnemyCount: 15,
    hunterEnemyCount: 0,
    spinnerEnemyCount: 0,
  },
  {
    mapHeight: 30,
    mapWidth: 30,
    levelColor: 'darkviolet',
    starCount: 18,
    obstacleCount: 4,
    wanderEnemyCount: 2,
    hunterEnemyCount: 0,
    spinnerEnemyCount: 2,
  },

  {
    mapHeight: 30,
    mapWidth: 50,
    levelColor: 'crimson',
    starCount: 40,
    obstacleCount: 20,
    wanderEnemyCount: 0,
    hunterEnemyCount: 1,
    spinnerEnemyCount: 2,
  },
  {
    mapHeight: 40,
    mapWidth: 30,
    levelColor: 'darkred',
    starCount: 10,
    obstacleCount: 15,
    wanderEnemyCount: 2,
    hunterEnemyCount: 2,
    spinnerEnemyCount: 2,
  },
  {
    mapHeight: 30,
    mapWidth: 30,
    levelColor: 'maroon',
    starCount: 30,
    obstacleCount: 10,
    wanderEnemyCount: 0,
    hunterEnemyCount: 0,
    spinnerEnemyCount: 3,
  },
  {
    mapHeight: 25,
    mapWidth: 25,
    levelColor: 'firebrick',
    starCount: 13,
    obstacleCount: 8,
    wanderEnemyCount: 3,
    hunterEnemyCount: 1,
    spinnerEnemyCount: 2,
  },
]

const endLevel = {
  mapHeight: 15,
  mapWidth: 15,
  levelColor: 'black',
  starCount: 0,
  obstacleCount: 1,
  wanderEnemyCount: 0,
  hunterEnemyCount: 0,
  spinnerEnemyCount: 0,
}

export const allStarCount = levels.map(({ starCount }) => starCount).reduce((a, b) => a + b)

export const useStore = create((set) => ({
  isPlayerAlive: true,
  lives: 3,
  level: 0,
  playerPosition: [0, 0.5, 0],
  collectedStars: 0,
  collectedStarsOnLevel: 0,
  isGateOpen: false,
  isGameOver: false,
  isGameFinished: false,
  ...levels[0],
  collectStar: () =>
    set((state) => ({
      collectedStarsOnLevel: state.collectedStarsOnLevel + 1,
      isGateOpen: state.collectedStarsOnLevel + 1 >= state.starCount,
    })),
  looseLife: () => set((state) => ({ lives: state.lives - 1, isPlayerAlive: false, isGameOver: state.lives - 1 <= 0 })),
  restart: (playerPosition) => set(() => ({ isPlayerAlive: true, playerPosition })),
  loadNextLevel: () =>
    set((state) => ({
      level: state.level + 1,
      isGateOpen: false,
      collectedStars: state.collectedStars + state.collectedStarsOnLevel,
      collectedStarsOnLevel: 0,
      isGameFinished: state.level + 1 === levels.length,
      ...(state.level + 1 === levels.length ? endLevel : levels[state.level + 1]),
    })),
}))

export const initialState = useStore.getState()
